/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package universiteelektroniksistem;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import com.mysql.jdbc.Statement;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hasalp
 */
public class academician_gui extends javax.swing.JFrame {

    /**
     * Creates new form student_gui
     */
    int selectedAcademician;
    FileInputStream fis = null;
    File file = null;
    
    public academician_gui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addAcademicianFrame = new javax.swing.JFrame();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        info1_tf = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        info2_tf = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        info3_tf = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        info4_tf = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        add_button = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        info6_tf = new javax.swing.JTextField();
        info5_cb = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        info7_tf = new javax.swing.JTextField();
        chooseImage = new javax.swing.JButton();
        changeAcademician = new javax.swing.JFrame();
        jPanel4 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        info1_tf1 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        info2_tf1 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        info3_tf1 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        change_button = new javax.swing.JButton();
        info4_tf1 = new javax.swing.JTextField();
        info6_tf1 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        info5_cb1 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        fileChooser = new javax.swing.JFileChooser();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        mainMenu_button = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        update_button = new javax.swing.JButton();
        addAcademician_button = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        delete_tf = new javax.swing.JTextField();
        delete_button = new javax.swing.JButton();
        search_button = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        academician_table = new javax.swing.JTable();

        addAcademicianFrame.setMinimumSize(new java.awt.Dimension(390, 417));
        addAcademicianFrame.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                addAcademicianFrameWindowActivated(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(254, 254, 254));
        jPanel3.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel3.setName(""); // NOI18N
        jPanel3.setPreferredSize(new java.awt.Dimension(350, 337));
        jPanel3.setRequestFocusEnabled(false);

        jLabel2.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Akademisyen Ekle");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Akademisyen No:");

        info1_tf.setEditable(false);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Akademisyen İsmi :");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Akademisyen Soyismi :");

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Akademisyen Uzmanlığı :");

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Akademisyen Rütbesi :");

        add_button.setBackground(new java.awt.Color(254, 254, 254));
        add_button.setText("Ekle");
        add_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_buttonActionPerformed(evt);
            }
        });

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Akademisyen Tel No :");

        info5_cb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Araştırma Görevlisi", "Çevirmen", "Okutman", "Öğretim Görevlisi", "Uzman", "Araştırma Profesörü", "Yardımcı Doçent", "Doçent", "Profesör", "Ordinaryüs" }));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo50x50.png"))); // NOI18N
        jLabel7.setText("EU");

        jLabel12.setText("Akademisyen Fotografi :");

        info7_tf.setEditable(false);

        chooseImage.setText("Seç");
        chooseImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseImageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(add_button, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(info1_tf)
                            .addComponent(info2_tf)
                            .addComponent(info3_tf)
                            .addComponent(info4_tf)
                            .addComponent(info6_tf)
                            .addComponent(info5_cb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(info7_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chooseImage)
                        .addGap(2, 2, 2)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(info1_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(info2_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(info3_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(info4_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(info5_cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(info6_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(info7_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chooseImage))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(add_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7))
                .addContainerGap())
        );

        javax.swing.GroupLayout addAcademicianFrameLayout = new javax.swing.GroupLayout(addAcademicianFrame.getContentPane());
        addAcademicianFrame.getContentPane().setLayout(addAcademicianFrameLayout);
        addAcademicianFrameLayout.setHorizontalGroup(
            addAcademicianFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        addAcademicianFrameLayout.setVerticalGroup(
            addAcademicianFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)
        );

        changeAcademician.setMinimumSize(new java.awt.Dimension(379, 453));
        changeAcademician.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                changeAcademicianWindowActivated(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(254, 254, 254));
        jPanel4.setMinimumSize(new java.awt.Dimension(363, 400));
        jPanel4.setPreferredSize(new java.awt.Dimension(363, 400));
        jPanel4.setRequestFocusEnabled(false);

        jLabel15.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Akademisyen Düzenle");

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText("Akademisyen No:");

        info1_tf1.setEditable(false);

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel17.setText("Akademisyen Adı :");

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel18.setText("Akademisyen Soyadı :");

        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel19.setText("Akademisyen Uzmanlığı :");

        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel21.setText("Akademisyen Rütbesi :");

        change_button.setBackground(new java.awt.Color(254, 254, 254));
        change_button.setText("Düzenle");
        change_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                change_buttonActionPerformed(evt);
            }
        });

        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel22.setText("Akademisyen Tel No :");

        info5_cb1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Araştırma Görevlisi", "Çevirmen", "Okutman", "Öğretim Görevlisi", "Uzman", "Araştırma Profesörü", "Yardımcı Doçent", "Doçent", "Profesör", "Ordinaryüs" }));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo50x50.png"))); // NOI18N
        jLabel8.setText("EU");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(info1_tf1)
                            .addComponent(info2_tf1)
                            .addComponent(info3_tf1)
                            .addComponent(info4_tf1)
                            .addComponent(info6_tf1)
                            .addComponent(info5_cb1, javax.swing.GroupLayout.Alignment.TRAILING, 0, 222, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                        .addGap(41, 41, 41)
                        .addComponent(change_button, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(info1_tf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(info2_tf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(info3_tf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(info4_tf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(info5_cb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(info6_tf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(change_button, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout changeAcademicianLayout = new javax.swing.GroupLayout(changeAcademician.getContentPane());
        changeAcademician.getContentPane().setLayout(changeAcademicianLayout);
        changeAcademicianLayout.setHorizontalGroup(
            changeAcademicianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        changeAcademicianLayout.setVerticalGroup(
            changeAcademicianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        fileChooser.setAcceptAllFileFilterUsed(false);
        fileChooser.setFileFilter(new FileNameExtensionFilter("Image files", "jpg","png", "tif"));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EU - Akademisyen İşlemleri");
        setIconImage(new ImageIcon(getClass().getResource("/images/logo50x50.png")).getImage());

        jPanel1.setBackground(new java.awt.Color(254, 254, 254));

        jLabel1.setText("Akademisyen İşlemleri");

        mainMenu_button.setBackground(new java.awt.Color(254, 254, 254));
        mainMenu_button.setText("Ana Menü");
        mainMenu_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainMenu_buttonActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(225, 232, 255));

        update_button.setBackground(new java.awt.Color(254, 254, 254));
        update_button.setText("Tüm Tabloyu Görüntüle");
        update_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_buttonActionPerformed(evt);
            }
        });

        addAcademician_button.setBackground(new java.awt.Color(254, 254, 254));
        addAcademician_button.setText("Akademisyen Ekle");
        addAcademician_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAcademician_buttonActionPerformed(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Akademisyen No");

        delete_button.setBackground(new java.awt.Color(254, 254, 254));
        delete_button.setText("Sil");
        delete_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_buttonActionPerformed(evt);
            }
        });

        search_button.setBackground(new java.awt.Color(254, 254, 254));
        search_button.setText("Arama Yap");
        search_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_buttonActionPerformed(evt);
            }
        });

        jLabel14.setText("<html>Akademisyen Bilgilerini<br>Düzenlemek İçin Listede<br>Çift Tıklayın</html>");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(update_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addAcademician_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(delete_tf)
                    .addComponent(delete_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(search_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(update_button, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addAcademician_button, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(delete_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(delete_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(search_button)
                .addGap(62, 62, 62)
                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                .addContainerGap())
        );

        academician_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Akademisyen No", "Akademisyen İsmi", "Akademisyen Soyismi", "Akademisyen Uzmanlığı", "Akademisyen Rütbesi", "Akademisyen Tel No"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        academician_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                academician_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(academician_table);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 799, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(mainMenu_button)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(mainMenu_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 3, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void update_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_buttonActionPerformed
        
        academician_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Akademisyen No", "Akademisyen İsmi", "Akademisyen Soyismi", "Akademisyen Uzmanliği", "Akademisyen Rütbesi", "Akademisyen Tel No"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        
        DefaultTableModel model = (DefaultTableModel) academician_table.getModel();
        
        try {
            Connection connect = new db_connection().connect;
            Statement stm = (Statement) connect.createStatement();
            ResultSet rs = (ResultSet) stm.executeQuery("SELECT akademisyen_id,akademisyen_ismi,akademisyen_soyismi,akademisyen_uzmanlik,akademisyen_rutbesi,akademisyen_telno FROM akademisyenler");
            
            while(rs.next()){
                model.addRow(new Object[]{
                    rs.getInt("akademisyen_id"),
                    rs.getString("akademisyen_ismi"),
                    rs.getString("akademisyen_soyismi"),
                    rs.getString("akademisyen_uzmanlik"),
                    rs.getInt("akademisyen_rutbesi"),
                    rs.getString("akademisyen_telno")
                });
            }
            
            academician_table.setModel(model);
            
            connect.close();
            
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(academician_gui.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_update_buttonActionPerformed

    private void mainMenu_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainMenu_buttonActionPerformed
        mainMenu menu = new mainMenu();
        this.setVisible(false);
        menu.setVisible(true);
    }//GEN-LAST:event_mainMenu_buttonActionPerformed

    private void add_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_buttonActionPerformed
        try {
            Connection connect = new db_connection().connect;
            //insert academician
            PreparedStatement prep_stm = (PreparedStatement) connect.prepareStatement("insert into akademisyenler(akademisyen_id,akademisyen_ismi,akademisyen_soyismi,akademisyen_uzmanlik,akademisyen_rutbesi,akademisyen_telno,akademisyen_resim) values(?,?,?,?,?,?,?)");
            
            prep_stm.setInt(1, Integer.parseInt(info1_tf.getText()));
            prep_stm.setString(2, info2_tf.getText());
            prep_stm.setString(3, info3_tf.getText());
            prep_stm.setString(4, info4_tf.getText());
            prep_stm.setInt(5, info5_cb.getSelectedIndex());
            prep_stm.setString(6, info6_tf.getText());
            if(fis!=null){
                prep_stm.setBinaryStream(7, fis, file.length());
            }else{
                prep_stm.setBinaryStream(7, null);
            }
            prep_stm.execute();
            //insert log
            
            Statement delete_log = (Statement) connect.createStatement();
            delete_log.executeUpdate("DELETE FROM log ORDER BY date ASC limit 1");
            delete_log.close();
            
            PreparedStatement prep_stm2 = (PreparedStatement) connect.prepareStatement("INSERT INTO log(date,userid,log) VALUES(?,?,?) ");
            prep_stm2.setString(1, new SimpleDateFormat("yyyy/MM/dd HH:mm:ss").format(Calendar.getInstance().getTime()));
            prep_stm2.setString(2, UserInfo.userID);
            prep_stm2.setString(3, Integer.parseInt(info1_tf.getText())+" Academician Inserted");
            prep_stm2.execute();
            
            
            JOptionPane.showMessageDialog(rootPane, "Akademisyen Eklendi.");
            addAcademicianFrame.setVisible(false);
            
            prep_stm2.close();
            prep_stm.close();
            connect.close();
        } catch (SQLException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(rootPane, "Girdiğiniz Bilgilerde Yanlışlık Var !!.");
            Logger.getLogger(academician_gui.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_add_buttonActionPerformed

    private void addAcademician_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAcademician_buttonActionPerformed
        addAcademicianFrame.setVisible(true);
    }//GEN-LAST:event_addAcademician_buttonActionPerformed

    private void delete_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_buttonActionPerformed
        
        int reply = JOptionPane.showConfirmDialog(null, "Kayidin silinmesine emin misiniz ?", "Silinsin mi?",  JOptionPane.YES_NO_OPTION);
        
        if(reply == JOptionPane.YES_OPTION){
            try {
                //delete
                Connection connect = new db_connection().connect;
                PreparedStatement prep_stm = (PreparedStatement) connect.prepareStatement("DELETE FROM akademisyenler WHERE akademisyen_id = ? ");
                prep_stm.setInt(1, Integer.parseInt(delete_tf.getText()));
                prep_stm.execute();
                //insert log
                Statement delete_log = (Statement) connect.createStatement();
                delete_log.executeUpdate("DELETE FROM log ORDER BY date ASC limit 1");
                delete_log.close();
                
                PreparedStatement prep_stm2 = (PreparedStatement) connect.prepareStatement("INSERT INTO log(date,userid,log) VALUES(?,?,?) ");
                prep_stm2.setString(1, new SimpleDateFormat("yyyy/MM/dd HH:mm:ss").format(Calendar.getInstance().getTime()));
                prep_stm2.setString(2, UserInfo.userID);
                prep_stm2.setString(3, delete_tf.getText()+" Academician Deleted");
                prep_stm2.execute();
                //close used objects
                prep_stm.close();
                prep_stm2.close();
                connect.close();
                JOptionPane.showMessageDialog(rootPane, "Akademisyen Silindi");
            } catch (SQLException | ClassNotFoundException ex) {
                Logger.getLogger(academician_gui.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_delete_buttonActionPerformed

    private void academician_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_academician_tableMouseClicked
        if(evt.getClickCount()==2){
            int selectedrow = academician_table.getSelectedRow();
            
            selectedAcademician = (int) academician_table.getValueAt(selectedrow, 0);
            
            changeAcademician.setVisible(true);
        }
    }//GEN-LAST:event_academician_tableMouseClicked

    private void change_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_change_buttonActionPerformed
        try {
            Connection connect = new db_connection().connect;
            
            String query = "UPDATE akademisyenler SET akademisyen_ismi=?,akademisyen_soyismi=?,akademisyen_uzmanlik=?,akademisyen_rutbesi=?,akademisyen_telno=? WHERE akademisyen_id=?";
            PreparedStatement prep_stm = (PreparedStatement) connect.prepareStatement(query);
            prep_stm.setString(1, info2_tf1.getText());
            prep_stm.setString(2, info3_tf1.getText());
            prep_stm.setString(3, info4_tf1.getText());
            prep_stm.setInt(4, info5_cb1.getSelectedIndex());
            prep_stm.setString(5, info6_tf1.getText());
            prep_stm.setInt(6, Integer.parseInt(info1_tf1.getText()));
            prep_stm.executeUpdate();
            //insert log
            Statement delete_log = (Statement) connect.createStatement();
            delete_log.executeUpdate("DELETE FROM log ORDER BY date ASC limit 1");
            delete_log.close();
            
            PreparedStatement prep_stm2 = (PreparedStatement) connect.prepareStatement("INSERT INTO log(date,userid,log) VALUES(?,?,?) ");
            prep_stm2.setString(1, new SimpleDateFormat("yyyy/MM/dd HH:mm:ss").format(Calendar.getInstance().getTime()));
            prep_stm2.setString(2, UserInfo.userID);
            prep_stm2.setString(3, info1_tf1.getText()+" Academician Changed");
            prep_stm2.execute();
            
            prep_stm.close();
            prep_stm2.close();
            connect.close();
            JOptionPane.showMessageDialog(rootPane, "Akademisyen Düzenlendi.");
            changeAcademician.setVisible(false);
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(academician_gui.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_change_buttonActionPerformed

    private void addAcademicianFrameWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_addAcademicianFrameWindowActivated
        try {
            Connection connect = new db_connection().connect;
            Statement stm = (Statement) connect.createStatement();
            ResultSet rs = (ResultSet) stm.executeQuery("SELECT akademisyen_id FROM akademisyenler");
            for(int id=0; ; id++){
                if(rs.next()){
                    if(id!=rs.getInt("akademisyen_id")){
                        info1_tf.setText(id+"");
                        break;
                    }
                }else{
                    info1_tf.setText(id+"");
                    break;
                }
            }
            
            connect.close();
            
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(academician_gui.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_addAcademicianFrameWindowActivated

    private void changeAcademicianWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_changeAcademicianWindowActivated
        try {
            
            Connection connect = new db_connection().connect;
            Statement stm = (Statement) connect.createStatement();
            ResultSet rs = (ResultSet) stm.executeQuery("SELECT * FROM akademisyenler");
            while(rs.next()){
                if(rs.getInt("akademisyen_id")==selectedAcademician){
                    info1_tf1.setText(String.valueOf(selectedAcademician));
                    info2_tf1.setText(rs.getString("akademisyen_ismi"));
                    info3_tf1.setText(rs.getString("akademisyen_soyismi"));
                    info4_tf1.setText(rs.getString("akademisyen_uzmanlik"));
                    info5_cb1.setSelectedIndex(rs.getInt("akademisyen_rutbesi"));
                    info6_tf1.setText(rs.getString("akademisyen_telno"));
                }
            }
            
            connect.close();
            
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(academician_gui.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_changeAcademicianWindowActivated

    private void search_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_buttonActionPerformed
        search(delete_tf.getText());
    }//GEN-LAST:event_search_buttonActionPerformed

    private void chooseImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseImageActionPerformed
        try {
            fileChooser.showOpenDialog(this);
            file = fileChooser.getSelectedFile(); 
            fis = new FileInputStream(file);
            info7_tf.setText(file.getAbsolutePath());
        } catch (FileNotFoundException ex) {
            Logger.getLogger(academician_gui.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Dosya seçilemedi");
        }
    }//GEN-LAST:event_chooseImageActionPerformed

    public void search(String search_element){
        int count = 0;
        academician_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Akademisyen No", "Akademisyen İsmi", "Akademisyen Soyismi", "Akademisyen Uzmanlığı", "Akademisyen Rütbesi", "Akademisyen Tel No"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        
        DefaultTableModel model = (DefaultTableModel) academician_table.getModel();
        
        try {
            Connection connect = new db_connection().connect;
            Statement stm = (Statement) connect.createStatement();
            ResultSet rs = (ResultSet) stm.executeQuery("SELECT * FROM akademisyenler");
            
            while(rs.next()){
                if(String.valueOf(rs.getInt("akademisyen_id")).contains(search_element) || rs.getString("akademisyen_ismi").contains(search_element) || rs.getString("akademisyen_soyismi").contains(search_element) || rs.getString("akademisyen_uzmanlik").contains(search_element) || String.valueOf(rs.getInt("akademisyen_rutbesi")).contains(search_element) || rs.getString("akademisyen_telno").contains(search_element)){
                    model.addRow(new Object[]{
                        rs.getInt("akademisyen_id"),
                        rs.getString("akademisyen_ismi"),
                        rs.getString("akademisyen_soyismi"),
                        rs.getString("akademisyen_uzmanlik"),
                        rs.getInt("akademisyen_rutbesi"),
                        rs.getString("akademisyen_telno"),
                    });
                    
                    count++;
                }
            }
            
            academician_table.setModel(model);
            
            JOptionPane.showMessageDialog(rootPane, "Aramanız için "+count+" kadar veri bulundu.");
            
            connect.close();
            
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(academician_gui.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(academician_gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(academician_gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(academician_gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(academician_gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new academician_gui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable academician_table;
    private javax.swing.JFrame addAcademicianFrame;
    private javax.swing.JButton addAcademician_button;
    private javax.swing.JButton add_button;
    private javax.swing.JFrame changeAcademician;
    private javax.swing.JButton change_button;
    private javax.swing.JButton chooseImage;
    private javax.swing.JButton delete_button;
    private javax.swing.JTextField delete_tf;
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JTextField info1_tf;
    private javax.swing.JTextField info1_tf1;
    private javax.swing.JTextField info2_tf;
    private javax.swing.JTextField info2_tf1;
    private javax.swing.JTextField info3_tf;
    private javax.swing.JTextField info3_tf1;
    private javax.swing.JTextField info4_tf;
    private javax.swing.JTextField info4_tf1;
    private javax.swing.JComboBox<String> info5_cb;
    private javax.swing.JComboBox<String> info5_cb1;
    private javax.swing.JTextField info6_tf;
    private javax.swing.JTextField info6_tf1;
    private javax.swing.JTextField info7_tf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton mainMenu_button;
    private javax.swing.JButton search_button;
    private javax.swing.JButton update_button;
    // End of variables declaration//GEN-END:variables
}
