/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package universiteelektroniksistem;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import com.mysql.jdbc.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hasalp
 */
public class courses_gui extends javax.swing.JFrame {

    /**
     * Creates new form student_gui
     */
    int selectedCourse;
    
    public courses_gui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addCourseFrame = new javax.swing.JFrame();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        info1_tf = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        info2_tf = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        info4_tf = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        info5_tf = new javax.swing.JTextField();
        add_button = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        info6_tf = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        info7_cb = new javax.swing.JComboBox<>();
        info8_cb = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        info3_cb = new javax.swing.JComboBox<>();
        changeCourse = new javax.swing.JFrame();
        jPanel4 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        info1_tf1 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        info2_tf1 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        info5_tf1 = new javax.swing.JTextField();
        change_button = new javax.swing.JButton();
        info4_tf1 = new javax.swing.JTextField();
        info6_tf1 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        info7_tf1 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        info8_cb1 = new javax.swing.JComboBox<>();
        jLabel24 = new javax.swing.JLabel();
        info3_cb1 = new javax.swing.JComboBox<>();
        popupMenu = new javax.swing.JPopupMenu();
        numberSearch = new javax.swing.JCheckBoxMenuItem();
        nameSearch = new javax.swing.JCheckBoxMenuItem();
        teacherSearch = new javax.swing.JCheckBoxMenuItem();
        departmentSearch = new javax.swing.JCheckBoxMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        mainMenu_button = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        update_button = new javax.swing.JButton();
        addCourse_button = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        delete_tf = new javax.swing.JTextField();
        delete_button = new javax.swing.JButton();
        search_button = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        searchProps_button = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        courses_table = new javax.swing.JTable();

        addCourseFrame.setMinimumSize(new java.awt.Dimension(341, 470));
        addCourseFrame.setResizable(false);
        addCourseFrame.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                addCourseFrameWindowActivated(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(254, 254, 254));
        jPanel3.setMinimumSize(new java.awt.Dimension(345, 472));
        jPanel3.setRequestFocusEnabled(false);

        jLabel2.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Ders Ekle");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Ders No:");

        info1_tf.setEditable(false);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Ders İsmi :");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Ders Öğretmeni :");

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Ders Süresi :");

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Ders Kredisi :");

        add_button.setBackground(new java.awt.Color(254, 254, 254));
        add_button.setText("Ekle");
        add_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_buttonActionPerformed(evt);
            }
        });

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Ders Sınıfı :");

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Bölüm ID :");

        info8_cb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Güz", "Bahar" }));

        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel20.setText("Ders Dönemi :");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(info1_tf)
                            .addComponent(info2_tf)
                            .addComponent(info4_tf)
                            .addComponent(info5_tf)
                            .addComponent(info6_tf)
                            .addComponent(info7_cb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(info8_cb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(info3_cb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 193, Short.MAX_VALUE)
                        .addComponent(add_button, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(info1_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(info2_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(info3_cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(info4_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(info5_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(info6_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(info7_cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(info8_cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(add_button)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout addCourseFrameLayout = new javax.swing.GroupLayout(addCourseFrame.getContentPane());
        addCourseFrame.getContentPane().setLayout(addCourseFrameLayout);
        addCourseFrameLayout.setHorizontalGroup(
            addCourseFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        addCourseFrameLayout.setVerticalGroup(
            addCourseFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        changeCourse.setMinimumSize(new java.awt.Dimension(357, 503));
        changeCourse.setResizable(false);
        changeCourse.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                changeCourseWindowActivated(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(254, 254, 254));
        jPanel4.setMinimumSize(new java.awt.Dimension(361, 505));
        jPanel4.setRequestFocusEnabled(false);

        jLabel15.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Ders Düzenle");

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText("Ders No:");

        info1_tf1.setEditable(false);

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel17.setText("Ders Adı :");

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel18.setText("Ders Öğretmeni :");

        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel19.setText("Ders Süresi :");

        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel21.setText("Ders Kredisi :");

        change_button.setBackground(new java.awt.Color(254, 254, 254));
        change_button.setText("Düzenle");
        change_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                change_buttonActionPerformed(evt);
            }
        });

        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel22.setText("Ders Sınıfı :");

        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel23.setText("Bölüm ID :");

        info8_cb1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Güz", "Bahar" }));

        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel24.setText("Ders Dönemi :");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(change_button, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(info1_tf1, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                            .addComponent(info2_tf1)
                            .addComponent(info5_tf1)
                            .addComponent(info4_tf1)
                            .addComponent(info6_tf1)
                            .addComponent(info7_tf1)
                            .addComponent(info8_cb1, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(info3_cb1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(info1_tf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(info2_tf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(info3_cb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(info4_tf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(info5_tf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(info6_tf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(info7_tf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(info8_cb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(change_button)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout changeCourseLayout = new javax.swing.GroupLayout(changeCourse.getContentPane());
        changeCourse.getContentPane().setLayout(changeCourseLayout);
        changeCourseLayout.setHorizontalGroup(
            changeCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        changeCourseLayout.setVerticalGroup(
            changeCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 475, Short.MAX_VALUE)
        );

        numberSearch.setText("Numara");
        popupMenu.add(numberSearch);

        nameSearch.setText("İsim");
        popupMenu.add(nameSearch);

        teacherSearch.setText("Öğretmen");
        popupMenu.add(teacherSearch);

        departmentSearch.setText("Bölüm");
        popupMenu.add(departmentSearch);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EU - Ders İşlemleri");
        setIconImage(new ImageIcon(getClass().getResource("/images/logo50x50.png")).getImage());

        jPanel1.setBackground(new java.awt.Color(254, 254, 254));

        jLabel1.setText("Ders İşlemleri");

        mainMenu_button.setBackground(new java.awt.Color(254, 254, 254));
        mainMenu_button.setText("Ana Menü");
        mainMenu_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainMenu_buttonActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(225, 232, 255));

        update_button.setBackground(new java.awt.Color(254, 254, 254));
        update_button.setText("Tüm Tabloyu Görüntüle");
        update_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_buttonActionPerformed(evt);
            }
        });

        addCourse_button.setBackground(new java.awt.Color(254, 254, 254));
        addCourse_button.setText("Ders Ekle");
        addCourse_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCourse_buttonActionPerformed(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText(" Ders No");

        delete_button.setBackground(new java.awt.Color(254, 254, 254));
        delete_button.setText("Sil");
        delete_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_buttonActionPerformed(evt);
            }
        });

        search_button.setBackground(new java.awt.Color(254, 254, 254));
        search_button.setText("Arama Yap");
        search_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_buttonActionPerformed(evt);
            }
        });

        jLabel14.setText("<html>Ders Bilgilerini<br>Düzenlemek İçin Listede<br>Çift Tıklayın</html>");

        searchProps_button.setBackground(new java.awt.Color(254, 254, 254));
        searchProps_button.setText("?");
        searchProps_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchProps_buttonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(update_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addCourse_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(delete_tf)
                    .addComponent(delete_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(search_button, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchProps_button, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(update_button, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addCourse_button, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(delete_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(delete_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(search_button)
                    .addComponent(searchProps_button, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(69, 69, 69)
                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                .addContainerGap())
        );

        courses_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ders No", "Ders İsmi", "Ders Öğretmeni", "Ders Zamanı", "Ders Kredisi", "Ders Sınıfı", "Bölüm ID", "Ders Dönemi"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        courses_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                courses_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(courses_table);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(mainMenu_button))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 799, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(mainMenu_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 3, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void update_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_buttonActionPerformed
        
        courses_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ders No", "Ders İsmi", "Ders Öğretmeni", "Ders Zamanı", "Ders Kredisi", "Ders Sınıfı", "Bölüm ID", "Ders Dönemi"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        
        DefaultTableModel model = (DefaultTableModel) courses_table.getModel();
        
        try {
            Connection connect = new db_connection().connect;
            Statement stm = (Statement) connect.createStatement();
            ResultSet rs = (ResultSet) stm.executeQuery("SELECT ders_id,ders_ismi,ders_ogretmeni,ders_suresi,ders_kredisi,ders_sinifi,bolum_id,ders_donemi FROM dersler");
            
            while(rs.next()){
                PreparedStatement prep_stm = (PreparedStatement) connect.prepareStatement("SELECT akademisyen_ismi,akademisyen_soyismi FROM akademisyenler WHERE akademisyen_id=?");
                prep_stm.setInt(1, rs.getInt("ders_ogretmeni"));
                ResultSet rs2 = prep_stm.executeQuery();
                rs2.next();
                model.addRow(new Object[]{
                    rs.getInt("ders_id"),
                    rs.getString("ders_ismi"),
                    rs2.getString("akademisyen_ismi")+" "+rs2.getString("akademisyen_soyismi"),
                    rs.getFloat("ders_suresi"),
                    rs.getInt("ders_kredisi"),
                    rs.getInt("ders_sinifi"),
                    rs.getInt("bolum_id"),
                    rs.getInt("ders_donemi")
                });
            }
            
            courses_table.setModel(model);
            
            connect.close();
            
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(courses_gui.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_update_buttonActionPerformed

    private void mainMenu_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainMenu_buttonActionPerformed
        mainMenu menu = new mainMenu();
        this.setVisible(false);
        menu.setVisible(true);
    }//GEN-LAST:event_mainMenu_buttonActionPerformed

    private void add_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_buttonActionPerformed
        try {
            Connection connect = new db_connection().connect;
            
            PreparedStatement prep_stm = (PreparedStatement) connect.prepareStatement("insert into dersler(ders_id,ders_ismi,ders_ogretmeni,ders_suresi,ders_kredisi,ders_sinifi,bolum_id,ders_donemi) values(?,?,?,?,?,?,?,?)");
            //insert course
            prep_stm.setInt(1, Integer.parseInt(info1_tf.getText()));
            prep_stm.setString(2, info2_tf.getText());
            prep_stm.setInt(3, info3_cb.getSelectedIndex());
            prep_stm.setFloat(4, Float.parseFloat(info4_tf.getText()));
            prep_stm.setInt(5, Integer.parseInt(info5_tf.getText()));
            prep_stm.setInt(6, Integer.parseInt(info6_tf.getText()));
            prep_stm.setInt(7, info7_cb.getSelectedIndex());
            prep_stm.setInt(8, info8_cb.getSelectedIndex());
            prep_stm.execute();
            //insert log
            Statement delete_log = (Statement) connect.createStatement();
            delete_log.executeUpdate("DELETE FROM log ORDER BY date ASC limit 1");
            delete_log.close();
            
            PreparedStatement prep_stm2 = (PreparedStatement) connect.prepareStatement("INSERT INTO log(date,userid,log) VALUES(?,?,?) ");
            prep_stm2.setString(1, new SimpleDateFormat("yyyy/MM/dd HH:mm:ss").format(Calendar.getInstance().getTime()));
            prep_stm2.setString(2, UserInfo.userID);
            prep_stm2.setString(3, info1_tf.getText()+" Course Inserted");
            prep_stm2.execute();
            
            JOptionPane.showMessageDialog(rootPane, "Ders Eklendi.");
            addCourseFrame.setVisible(false);
            prep_stm.close();
            prep_stm2.close();
            connect.close();
        } catch (SQLException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(rootPane, "Girdiğiniz Bilgilerde Yanlışlık Var !!.");
            Logger.getLogger(courses_gui.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_add_buttonActionPerformed

    private void addCourse_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCourse_buttonActionPerformed
        addCourseFrame.setVisible(true);
    }//GEN-LAST:event_addCourse_buttonActionPerformed

    private void delete_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_buttonActionPerformed
        
        int reply = JOptionPane.showConfirmDialog(null, "Kayidin silinmesine emin misiniz ?", "Silinsin mi?",  JOptionPane.YES_NO_OPTION);
        
        if(reply == JOptionPane.YES_OPTION){    
            try {
                Connection connect = new db_connection().connect;
                //delete course
                PreparedStatement prep_stm = (PreparedStatement) connect.prepareStatement("DELETE FROM dersler WHERE ders_id = ? ");
                prep_stm.setInt(1, Integer.parseInt(delete_tf.getText()));
                prep_stm.execute();
                //insert log
                
                Statement delete_log = (Statement) connect.createStatement();
                delete_log.executeUpdate("DELETE FROM log ORDER BY date ASC limit 1");
                delete_log.close();
                
                PreparedStatement prep_stm2 = (PreparedStatement) connect.prepareStatement("INSERT INTO log(date,userid,log) VALUES(?,?,?) ");
                prep_stm2.setString(1, new SimpleDateFormat("yyyy/MM/dd HH:mm:ss").format(Calendar.getInstance().getTime()));
                prep_stm2.setString(2, UserInfo.userID);
                prep_stm2.setString(3, delete_tf.getText()+" Course Deleted");
                prep_stm2.execute();
                
                prep_stm2.close();
                prep_stm.close();
                connect.close();
                JOptionPane.showMessageDialog(rootPane, "Ders Silindi");
            } catch (SQLException | ClassNotFoundException ex) {
                Logger.getLogger(courses_gui.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_delete_buttonActionPerformed

    private void search_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_buttonActionPerformed
        search(delete_tf.getText());
    }//GEN-LAST:event_search_buttonActionPerformed

    private void change_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_change_buttonActionPerformed
        try {
            Connection connect = new db_connection().connect;
            //change course
            String query = "UPDATE dersler SET ders_ismi=?,ders_ogretmeni=?,ders_suresi=?,ders_kredisi=?,ders_sinifi=?,bolum_id=?,ders_donemi=? WHERE ders_id=?";
            PreparedStatement prep_stm = (PreparedStatement) connect.prepareStatement(query);
            prep_stm.setString(1, info2_tf1.getText());
            prep_stm.setInt(2, info3_cb1.getSelectedIndex());
            prep_stm.setFloat(3, Float.parseFloat(info4_tf1.getText()));
            prep_stm.setInt(4, Integer.parseInt(info5_tf1.getText()));
            prep_stm.setInt(5, Integer.parseInt(info6_tf1.getText()));
            prep_stm.setInt(6, Integer.parseInt(info7_tf1.getText()));
            prep_stm.setInt(7, info8_cb1.getSelectedIndex());
            prep_stm.setInt(8, Integer.parseInt(info1_tf1.getText()));
            prep_stm.executeUpdate();
            
            //insert log
            
            Statement delete_log = (Statement) connect.createStatement();
            delete_log.executeUpdate("DELETE FROM log ORDER BY date ASC limit 1");
            delete_log.close();
            
            PreparedStatement prep_stm2 = (PreparedStatement) connect.prepareStatement("INSERT INTO log(date,userid,log) VALUES(?,?,?) ");
            prep_stm2.setString(1, new SimpleDateFormat("yyyy/MM/dd HH:mm:ss").format(Calendar.getInstance().getTime()));
            prep_stm2.setString(2, UserInfo.userID);
            prep_stm2.setString(3, info1_tf1.getText()+" Course Changed");
            prep_stm2.execute();
            
            prep_stm.close();
            prep_stm2.close();
            connect.close();
            JOptionPane.showMessageDialog(rootPane, "Ders Düzenlendi.");
            changeCourse.setVisible(false);
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(courses_gui.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_change_buttonActionPerformed

    private void addCourseFrameWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_addCourseFrameWindowActivated
        info7_cb.removeAllItems();
        info3_cb.removeAllItems();
        
        try {
            Connection connect = new db_connection().connect;
            Statement stm = (Statement) connect.createStatement();
            ResultSet rs = (ResultSet) stm.executeQuery("SELECT ders_id FROM dersler");
            for(int id=0; ; id++){
                if(rs.next()){
                    if(id!=rs.getInt("ders_id")){
                        info1_tf.setText(id+"");
                        break;
                    }
                }else{
                    info1_tf.setText(id+"");
                    break;
                }
            }
            
            rs.close();
            //add departments to combobox
            rs = (ResultSet) stm.executeQuery("Select bolum_ismi from bolumler");
            while(rs.next()){
                info7_cb.addItem(rs.getString("bolum_ismi"));
            }
            
            rs.close();
            //add teachers to combobox
            rs = (ResultSet) stm.executeQuery("Select akademisyen_ismi,akademisyen_soyismi from akademisyenler");
            while(rs.next()){
                info3_cb.addItem(rs.getString("akademisyen_ismi")+" "+rs.getString("akademisyen_soyismi"));
            }
            
            rs.close();
            
            connect.close();
            
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(courses_gui.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_addCourseFrameWindowActivated

    private void changeCourseWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_changeCourseWindowActivated
        info3_cb1.removeAllItems();
        
        try {
            
            Connection connect = new db_connection().connect;
            Statement stm = (Statement) connect.createStatement();
            
            //add teachers to combobox
            ResultSet rs = (ResultSet) stm.executeQuery("Select akademisyen_ismi,akademisyen_soyismi from akademisyenler");
            
            while(rs.next()){
                info3_cb1.addItem(rs.getString("akademisyen_ismi")+" "+rs.getString("akademisyen_soyismi"));
            }
            
            rs.close();
            
            rs = (ResultSet) stm.executeQuery("SELECT * FROM dersler");
            while(rs.next()){
                if(rs.getInt("ders_id")==selectedCourse){
                    info1_tf1.setText(String.valueOf(selectedCourse));
                    info2_tf1.setText(rs.getString("ders_ismi"));
                    info3_cb1.setSelectedIndex(rs.getInt("ders_ogretmeni"));
                    info4_tf1.setText(String.valueOf(rs.getFloat("ders_suresi")));
                    info5_tf1.setText(String.valueOf(rs.getInt("ders_kredisi")));
                    info6_tf1.setText(String.valueOf(rs.getInt("ders_sinifi")));
                    info7_tf1.setText(String.valueOf(rs.getInt("bolum_id")));
                    info8_cb1.setSelectedIndex(rs.getInt("ders_donemi"));
                }
            }
            
            connect.close();

            
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(courses_gui.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_changeCourseWindowActivated

    private void courses_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_courses_tableMouseClicked
        if(evt.getClickCount()==2){
            int selectedrow = courses_table.getSelectedRow();

            selectedCourse = (int) courses_table.getValueAt(selectedrow, 0);

            changeCourse.setVisible(true);
        }
    }//GEN-LAST:event_courses_tableMouseClicked

    private void searchProps_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchProps_buttonMouseClicked
        popupMenu.show(this, evt.getX(), evt.getY());
    }//GEN-LAST:event_searchProps_buttonMouseClicked

    public void search(String search_element){
        int count = 0;
        courses_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ders No", "Ders İsmi", "Ders Öğretmeni", "Ders Zamanı", "Ders Kredisi", "Ders Sınıfı", "Bölüm ID", "Ders Dönemi"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        
        DefaultTableModel model = (DefaultTableModel) courses_table.getModel();
        
        try {
            Connection connect = new db_connection().connect;
            Statement stm = (Statement) connect.createStatement();
            ResultSet rs = (ResultSet) stm.executeQuery("SELECT * FROM dersler");
            
            while(rs.next()){
                PreparedStatement prep_stm = (PreparedStatement) connect.prepareStatement("SELECT akademisyen_ismi,akademisyen_soyismi FROM akademisyenler WHERE akademisyen_id=?");
                prep_stm.setInt(1, rs.getInt("ders_ogretmeni"));
                ResultSet rs2 = prep_stm.executeQuery();
                rs2.next();
                if((String.valueOf(rs.getInt("ders_id")).contains(search_element) && numberSearch.isSelected()) || (rs.getString("ders_ismi").contains(search_element) && nameSearch.isSelected()) || (rs.getString("ders_ogretmeni").contains(search_element) && teacherSearch.isSelected()) || (String.valueOf(rs.getInt("bolum_id")).contains(search_element) && departmentSearch.isSelected())){
                    model.addRow(new Object[]{
                        rs.getInt("ders_id"),
                        rs.getString("ders_ismi"),
                        rs2.getString("akademisyen_ismi")+" "+rs2.getString("akademisyen_soyismi"),
                        rs.getFloat("ders_suresi"),
                        rs.getInt("ders_kredisi"),
                        rs.getInt("ders_sinifi"),
                        rs.getInt("bolum_id"),
                        rs.getInt("ders_donemi")
                    });
                    
                    count++;
                }
            }
            
            courses_table.setModel(model);
            
            JOptionPane.showMessageDialog(rootPane, "Aramanız için "+count+" kadar veri bulundu.");
            
            connect.close();
            
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(courses_gui.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(courses_gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(courses_gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(courses_gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(courses_gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new courses_gui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame addCourseFrame;
    private javax.swing.JButton addCourse_button;
    private javax.swing.JButton add_button;
    private javax.swing.JFrame changeCourse;
    private javax.swing.JButton change_button;
    private javax.swing.JTable courses_table;
    private javax.swing.JButton delete_button;
    private javax.swing.JTextField delete_tf;
    private javax.swing.JCheckBoxMenuItem departmentSearch;
    private javax.swing.JTextField info1_tf;
    private javax.swing.JTextField info1_tf1;
    private javax.swing.JTextField info2_tf;
    private javax.swing.JTextField info2_tf1;
    private javax.swing.JComboBox<String> info3_cb;
    private javax.swing.JComboBox<String> info3_cb1;
    private javax.swing.JTextField info4_tf;
    private javax.swing.JTextField info4_tf1;
    private javax.swing.JTextField info5_tf;
    private javax.swing.JTextField info5_tf1;
    private javax.swing.JTextField info6_tf;
    private javax.swing.JTextField info6_tf1;
    private javax.swing.JComboBox<String> info7_cb;
    private javax.swing.JTextField info7_tf1;
    private javax.swing.JComboBox<String> info8_cb;
    private javax.swing.JComboBox<String> info8_cb1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton mainMenu_button;
    private javax.swing.JCheckBoxMenuItem nameSearch;
    private javax.swing.JCheckBoxMenuItem numberSearch;
    private javax.swing.JPopupMenu popupMenu;
    private javax.swing.JButton searchProps_button;
    private javax.swing.JButton search_button;
    private javax.swing.JCheckBoxMenuItem teacherSearch;
    private javax.swing.JButton update_button;
    // End of variables declaration//GEN-END:variables
}
