/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package universiteelektroniksistem;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author hasalp
 */
public class mainMenu_nA extends javax.swing.JFrame {

    /**
     * Creates new form mainMenu
     */
    public mainMenu_nA() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        student_button = new javax.swing.JButton();
        department_button = new javax.swing.JButton();
        course_button = new javax.swing.JButton();
        academician_button = new javax.swing.JButton();
        syllabus_button = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        course_register = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Elektronik Üniversite");
        setIconImage(new ImageIcon(getClass().getResource("/images/logo50x50.png")).getImage());
        setMinimumSize(new java.awt.Dimension(563, 455));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(254, 254, 254));
        jPanel1.setMinimumSize(new java.awt.Dimension(563, 455));

        jLabel1.setText("Öğrenci Paneli");

        student_button.setBackground(new java.awt.Color(254, 254, 254));
        student_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/student_big.png"))); // NOI18N
        student_button.setText("Öğrenci Görüntüle");
        student_button.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/images/student_big.png"))); // NOI18N
        student_button.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        student_button.setOpaque(true);
        student_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                student_buttonActionPerformed(evt);
            }
        });

        department_button.setBackground(new java.awt.Color(254, 254, 254));
        department_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/department.png"))); // NOI18N
        department_button.setText("Bölüm Görüntüle");
        department_button.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/images/student_big.png"))); // NOI18N
        department_button.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        department_button.setOpaque(true);
        department_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                department_buttonActionPerformed(evt);
            }
        });

        course_button.setBackground(new java.awt.Color(254, 254, 254));
        course_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/course.png"))); // NOI18N
        course_button.setText("Ders Görüntüle");
        course_button.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/images/student_big.png"))); // NOI18N
        course_button.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        course_button.setOpaque(true);
        course_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                course_buttonActionPerformed(evt);
            }
        });

        academician_button.setBackground(new java.awt.Color(254, 254, 254));
        academician_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/academician.png"))); // NOI18N
        academician_button.setText("Akademisyen Görüntüle");
        academician_button.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/images/student_big.png"))); // NOI18N
        academician_button.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        academician_button.setOpaque(true);
        academician_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                academician_buttonActionPerformed(evt);
            }
        });

        syllabus_button.setBackground(new java.awt.Color(254, 254, 254));
        syllabus_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/schedule.png"))); // NOI18N
        syllabus_button.setText("Program Görüntüle");
        syllabus_button.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        syllabus_button.setOpaque(true);
        syllabus_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                syllabus_buttonActionPerformed(evt);
            }
        });

        jLabel2.setText("Kullanici Adi :");

        course_register.setBackground(new java.awt.Color(254, 254, 254));
        course_register.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/addCourse.png"))); // NOI18N
        course_register.setText("Ders Kaydı");
        course_register.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        course_register.setOpaque(true);
        course_register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                course_registerActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo100x100.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Elektronik Üniversitem");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel1)
                        .addGap(134, 134, 134)
                        .addComponent(jLabel2)
                        .addGap(15, 15, 15)
                        .addComponent(usernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(student_button, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(academician_button, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(department_button, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(course_register, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(course_button, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(syllabus_button, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(student_button)
                    .addComponent(academician_button))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(department_button)
                    .addComponent(course_register))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(course_button)
                    .addComponent(syllabus_button))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void student_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_student_buttonActionPerformed
        student_gui_nA gui = new student_gui_nA();
        this.setVisible(false);
        gui.setVisible(true);
    }//GEN-LAST:event_student_buttonActionPerformed

    private void department_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_department_buttonActionPerformed
        department_gui_nA gui = new department_gui_nA();
        this.setVisible(false);
        gui.setVisible(true);
    }//GEN-LAST:event_department_buttonActionPerformed

    private void course_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_course_buttonActionPerformed
        courses_gui_nA gui = new courses_gui_nA();
        this.setVisible(false);
        gui.setVisible(true);
    }//GEN-LAST:event_course_buttonActionPerformed

    private void academician_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_academician_buttonActionPerformed
        academician_gui_nA gui = new academician_gui_nA();
        this.setVisible(false);
        gui.setVisible(true);
    }//GEN-LAST:event_academician_buttonActionPerformed

    private void syllabus_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_syllabus_buttonActionPerformed
        syllabus_gui_nA gui = new syllabus_gui_nA();
        this.setVisible(false);
        gui.setVisible(true);
    }//GEN-LAST:event_syllabus_buttonActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        UserInfo uinfo = new UserInfo();
        usernameLabel.setText(uinfo.username);
    }//GEN-LAST:event_formWindowActivated

    private void course_registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_course_registerActionPerformed
        courseRegister_gui gui = new courseRegister_gui();
        this.setVisible(false);
        gui.setVisible(true);
    }//GEN-LAST:event_course_registerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainMenu_nA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainMenu_nA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainMenu_nA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainMenu_nA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainMenu_nA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton academician_button;
    private javax.swing.JButton course_button;
    private javax.swing.JButton course_register;
    private javax.swing.JButton department_button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton student_button;
    private javax.swing.JButton syllabus_button;
    public javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables
}
