/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package universiteelektroniksistem;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import com.mysql.jdbc.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hasalp
 */
public class student_gui extends javax.swing.JFrame {

    /**
     * Creates new form student_gui
     */
    int selectedStudent;
    
    public student_gui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addStudentFrame = new javax.swing.JFrame();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        info1_tf = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        info2_tf = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        info3_tf = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        info4_sp = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        info5_cb = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        info6_tf = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        info7_tf = new javax.swing.JTextField();
        info8_tf = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        add_button = new javax.swing.JButton();
        info9_dp = new com.github.lgooddatepicker.components.DatePicker();
        jScrollPane2 = new javax.swing.JScrollPane();
        info10_textArea = new javax.swing.JTextArea();
        jLabel25 = new javax.swing.JLabel();
        changeStudent = new javax.swing.JFrame();
        jPanel4 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        info1_tf1 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        info2_tf1 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        info3_tf1 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        info4_sp1 = new javax.swing.JSpinner();
        jLabel20 = new javax.swing.JLabel();
        info5_cb1 = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        info6_tf1 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        info7_tf1 = new javax.swing.JTextField();
        info8_tf1 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        change_button = new javax.swing.JButton();
        info9_dp1 = new com.github.lgooddatepicker.components.DatePicker();
        jScrollPane3 = new javax.swing.JScrollPane();
        info10_textArea1 = new javax.swing.JTextArea();
        jLabel26 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        mainMenu_button = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        update_button = new javax.swing.JButton();
        addStudent_button = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        delete_tf = new javax.swing.JTextField();
        delete_button = new javax.swing.JButton();
        search_button = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        student_table = new javax.swing.JTable();

        addStudentFrame.setMinimumSize(new java.awt.Dimension(376, 598));
        addStudentFrame.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                addStudentFrameWindowActivated(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(254, 254, 254));
        jPanel3.setMinimumSize(new java.awt.Dimension(356, 595));
        jPanel3.setRequestFocusEnabled(false);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Öğrenci Ekle");
        jLabel2.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N

        jLabel4.setText("Öğrenci No:");

        info1_tf.setEditable(false);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Ad :");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Soyad :");

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Sınıfı :");

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Bölümü :");

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Ortalaması :");

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("E-Mail :");

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Tel No :");

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Kayıt Tarihi :");

        add_button.setText("Ekle");
        add_button.setBackground(new java.awt.Color(254, 254, 254));
        add_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_buttonActionPerformed(evt);
            }
        });

        info10_textArea.setColumns(20);
        info10_textArea.setRows(5);
        jScrollPane2.setViewportView(info10_textArea);

        jLabel25.setText("Kayit Nedeni :");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(add_button, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(info1_tf)
                            .addComponent(info2_tf)
                            .addComponent(info3_tf)
                            .addComponent(info4_sp)
                            .addComponent(info5_cb, 0, 231, Short.MAX_VALUE)
                            .addComponent(info6_tf)
                            .addComponent(info7_tf)
                            .addComponent(info8_tf)
                            .addComponent(info9_dp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(info1_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(info2_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(info3_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(info4_sp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(info5_cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(info6_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(info7_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(info8_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(info9_dp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(add_button)
                .addContainerGap())
        );

        javax.swing.GroupLayout addStudentFrameLayout = new javax.swing.GroupLayout(addStudentFrame.getContentPane());
        addStudentFrame.getContentPane().setLayout(addStudentFrameLayout);
        addStudentFrameLayout.setHorizontalGroup(
            addStudentFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        addStudentFrameLayout.setVerticalGroup(
            addStudentFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        changeStudent.setMinimumSize(new java.awt.Dimension(377, 597));
        changeStudent.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                changeStudentWindowActivated(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(254, 254, 254));
        jPanel4.setMinimumSize(new java.awt.Dimension(356, 589));
        jPanel4.setRequestFocusEnabled(false);

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Öğrenci Düzenle");
        jLabel15.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText("Öğrenci No:");

        info1_tf1.setEditable(false);

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel17.setText("Ad :");

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel18.setText("Soyad :");

        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel19.setText("Sınıfı :");

        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel20.setText("Bölümü :");

        info5_cb1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bilgisayar Mühendisliği", "Mimarlık", "İnşaat Mühendisliği", "Enerji Sistemleri", "Mekatronik Mühendisliği", "Elektrik ve Elektronik" }));

        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel21.setText("Ortalaması :");

        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel22.setText("E-Mail :");

        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel23.setText("Tel No :");

        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel24.setText("Kayıt Tarihi :");

        change_button.setText("Düzenle");
        change_button.setBackground(new java.awt.Color(254, 254, 254));
        change_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                change_buttonActionPerformed(evt);
            }
        });

        info10_textArea1.setColumns(20);
        info10_textArea1.setRows(5);
        jScrollPane3.setViewportView(info10_textArea1);

        jLabel26.setText("Kayit Nedeni :");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(change_button, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                            .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                            .addComponent(info1_tf1)
                            .addComponent(info2_tf1)
                            .addComponent(info3_tf1)
                            .addComponent(info4_sp1)
                            .addComponent(info5_cb1, 0, 231, Short.MAX_VALUE)
                            .addComponent(info6_tf1)
                            .addComponent(info7_tf1)
                            .addComponent(info8_tf1)
                            .addComponent(info9_dp1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(info1_tf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(info2_tf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(info3_tf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(info4_sp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(info5_cb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(info6_tf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(info7_tf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(info8_tf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(info9_dp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(change_button)
                .addContainerGap())
        );

        javax.swing.GroupLayout changeStudentLayout = new javax.swing.GroupLayout(changeStudent.getContentPane());
        changeStudent.getContentPane().setLayout(changeStudentLayout);
        changeStudentLayout.setHorizontalGroup(
            changeStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        changeStudentLayout.setVerticalGroup(
            changeStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(changeStudentLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EU - Öğrenci İşlemleri");
        setIconImage(new ImageIcon(getClass().getResource("/images/logo50x50.png")).getImage());

        jPanel1.setBackground(new java.awt.Color(254, 254, 254));

        jLabel1.setText("Öğrenci İşlemleri");

        mainMenu_button.setText("Ana Menü");
        mainMenu_button.setBackground(new java.awt.Color(254, 254, 254));
        mainMenu_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainMenu_buttonActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(225, 232, 255));

        update_button.setText("Tüm Tabloyu Görüntüle");
        update_button.setBackground(new java.awt.Color(254, 254, 254));
        update_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_buttonActionPerformed(evt);
            }
        });

        addStudent_button.setText("Öğrenci Ekle");
        addStudent_button.setBackground(new java.awt.Color(254, 254, 254));
        addStudent_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStudent_buttonActionPerformed(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Öğrenci No");

        delete_button.setText("Sil");
        delete_button.setBackground(new java.awt.Color(254, 254, 254));
        delete_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_buttonActionPerformed(evt);
            }
        });

        search_button.setText("Arama Yap");
        search_button.setBackground(new java.awt.Color(254, 254, 254));
        search_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_buttonActionPerformed(evt);
            }
        });

        jLabel14.setText("<html>Öğrenci Bilgilerini<br>Düzenlemek İçin Listede<br>Çift Tıklayın</html>");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(update_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addStudent_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(delete_tf)
                    .addComponent(delete_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(search_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(update_button, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addStudent_button, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(delete_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(delete_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(search_button)
                .addGap(69, 69, 69)
                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                .addContainerGap())
        );

        student_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Öğrenci No", "Ad", "Soyad", "Sınıf", "Bölüm İsmi", "Ortalama", "E-mail", "Tel No", "Kayıt Tarihi", "Kayıt Nedeni"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        student_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                student_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(student_table);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 799, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(mainMenu_button)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(mainMenu_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 3, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void update_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_buttonActionPerformed
        
        student_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Öğrenci No", "Ad", "Soyad", "Sınıf", "Bölüm İsmi", "Ortalama", "E-mail", "Tel No", "Kayıt Tarihi", "Kayıt Nedeni"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        
        DefaultTableModel model = (DefaultTableModel) student_table.getModel();
        
        try {
            Connection connect = new db_connection().connect;
            Statement stm = (Statement) connect.createStatement();
            ResultSet rs = (ResultSet) stm.executeQuery("SELECT ogrenci_id,ogrenci_ismi,ogrenci_soyismi,ogrenci_sinifi,bolum_ismi,ogrenci_ortalamasi,ogrenci_email,ogrenci_telno,ogrenci_kayittarihi,kayit_nedeni FROM ogrenciler,bolumler where bolumler.bolum_id=ogrenciler.bolum_id");
            
            while(rs.next()){
                model.addRow(new Object[]{
                    rs.getInt("ogrenci_id"),
                    rs.getString("ogrenci_ismi"),
                    rs.getString("ogrenci_soyismi"),
                    rs.getInt("ogrenci_sinifi"),
                    rs.getString("bolum_ismi"),
                    rs.getFloat("ogrenci_ortalamasi"),
                    rs.getString("ogrenci_email"),
                    rs.getString("ogrenci_telno"),
                    rs.getString("ogrenci_kayittarihi"),
                    rs.getString("kayit_nedeni")
                });
            }
            
            student_table.setModel(model);
            
            connect.close();
            
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(student_gui.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_update_buttonActionPerformed

    private void mainMenu_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainMenu_buttonActionPerformed
        mainMenu menu = new mainMenu();
        this.setVisible(false);
        menu.setVisible(true);
    }//GEN-LAST:event_mainMenu_buttonActionPerformed

    private void add_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_buttonActionPerformed
        try {
            Connection connect = new db_connection().connect;
            //insert student
            PreparedStatement prep_stm = (PreparedStatement) connect.prepareStatement("insert into ogrenciler(ogrenci_id,ogrenci_ismi,ogrenci_soyismi,ogrenci_sinifi,bolum_id,ogrenci_ortalamasi,ogrenci_email,ogrenci_telno,ogrenci_kayittarihi,kayit_nedeni) values(?,?,?,?,?,?,?,?,?,?)");
            prep_stm.setString(1, info1_tf.getText());
            prep_stm.setString(2, info2_tf.getText());
            prep_stm.setString(3, info3_tf.getText());
            prep_stm.setInt(4, (int) info4_sp.getValue());
            prep_stm.setInt(5, info5_cb.getSelectedIndex());
            prep_stm.setString(6, info6_tf.getText());
            prep_stm.setString(7, info7_tf.getText());
            prep_stm.setString(8, info8_tf.getText());
            prep_stm.setString(9, info9_dp.getText());
            prep_stm.setString(10, info10_textArea.getText());
            
            prep_stm.execute();
            prep_stm.close();
            //increase student amount
            prep_stm = (PreparedStatement) connect.prepareStatement("UPDATE bolumler SET bolum_ogrencisayisi = bolum_ogrencisayisi+1 WHERE bolum_id = ?");
            prep_stm.setInt(1, info5_cb.getSelectedIndex());
            
            prep_stm.executeUpdate();
            prep_stm.close();
            
            //insert log
            
            Statement delete_log = (Statement) connect.createStatement();
                delete_log.executeUpdate("DELETE FROM log ORDER BY date ASC limit 1");
                delete_log.close();
            
            PreparedStatement prep_stm2 = (PreparedStatement) connect.prepareStatement("INSERT INTO log(date,userid,log) VALUES(?,?,?) ");
            prep_stm2.setString(1, new SimpleDateFormat("yyyy/MM/dd HH:mm:ss").format(Calendar.getInstance().getTime()));
            prep_stm2.setString(2, UserInfo.userID);
            prep_stm2.setString(3, info1_tf.getText()+" Student Inserted");
            prep_stm2.execute();
            prep_stm2.close();
            
            JOptionPane.showMessageDialog(rootPane, "Öğrenci Eklendi.");
            addStudentFrame.setVisible(false);
            
            connect.close();
        } catch (SQLException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(rootPane, "Yanlış ve ya kullanılmayan bir öğrenci numarası girdiniz.");
            Logger.getLogger(student_gui.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_add_buttonActionPerformed

    private void addStudent_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStudent_buttonActionPerformed
        addStudentFrame.setVisible(true);
    }//GEN-LAST:event_addStudent_buttonActionPerformed

    private void delete_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_buttonActionPerformed
        int reply = JOptionPane.showConfirmDialog(null, "Kayidin silinmesine emin misiniz ?", "Silinsin mi?",  JOptionPane.YES_NO_OPTION);
        
        if(reply == JOptionPane.YES_OPTION){
            //decrease student amount
            try {
                Connection connect = new db_connection().connect;
                PreparedStatement prep_stm = (PreparedStatement) connect.prepareStatement("SELECT bolum_id FROM ogrenciler WHERE ogrenci_id = ? ");
                prep_stm.setInt(1, Integer.parseInt(delete_tf.getText()));
                ResultSet rs = (ResultSet) prep_stm.executeQuery();

                if(rs.next()){
                    prep_stm = (PreparedStatement) connect.prepareStatement("UPDATE bolumler SET bolum_ogrencisayisi = bolum_ogrencisayisi-1 WHERE bolum_id = ?");
                    prep_stm.setInt(1, rs.getInt("bolum_id"));

                    prep_stm.executeUpdate();
                    prep_stm.close();
                }

                //delete student
                prep_stm = (PreparedStatement) connect.prepareStatement("DELETE FROM ogrenciler WHERE ogrenci_id = ? ");
                prep_stm.setInt(1, Integer.parseInt(delete_tf.getText()));
                prep_stm.execute();
                
                //insert log
                
                Statement delete_log = (Statement) connect.createStatement();
                delete_log.executeUpdate("DELETE FROM log ORDER BY date ASC limit 1");
                delete_log.close();
                
                PreparedStatement prep_stm2 = (PreparedStatement) connect.prepareStatement("INSERT INTO log(date,userid,log) VALUES(?,?,?) ");
                prep_stm2.setString(1, new SimpleDateFormat("yyyy/MM/dd HH:mm:ss").format(Calendar.getInstance().getTime()));
                prep_stm2.setString(2, UserInfo.userID);
                prep_stm2.setString(3, delete_tf.getText()+" Student Deleted");
                prep_stm2.execute();
                
                prep_stm.close();
                prep_stm2.close();
                connect.close();
                JOptionPane.showMessageDialog(rootPane, "Öğrenci Silindi");
            } catch (SQLException | ClassNotFoundException ex) {
                Logger.getLogger(student_gui.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_delete_buttonActionPerformed

    private void search_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_buttonActionPerformed
        search(delete_tf.getText());
    }//GEN-LAST:event_search_buttonActionPerformed

    private void student_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_student_tableMouseClicked
        if(evt.getClickCount()==2){
            int selectedrow = student_table.getSelectedRow();
            
            selectedStudent = (int) student_table.getValueAt(selectedrow, 0);
            
            changeStudent.setVisible(true);
        }
    }//GEN-LAST:event_student_tableMouseClicked

    private void change_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_change_buttonActionPerformed
        try {
            Connection connect = new db_connection().connect;
            
            //update student
            String query = "UPDATE ogrenciler SET ogrenci_ismi=?,ogrenci_soyismi=?,ogrenci_sinifi=?,bolum_id=?,ogrenci_ortalamasi=?,ogrenci_email=?,ogrenci_telno=?,ogrenci_kayittarihi=?,kayit_nedeni=? WHERE ogrenci_id=?";
            PreparedStatement prep_stm = (PreparedStatement) connect.prepareStatement(query);
            prep_stm.setString(1, info2_tf1.getText());
            prep_stm.setString(2, info3_tf1.getText());
            prep_stm.setInt(3, (int) info4_sp1.getValue());
            prep_stm.setInt(4, info5_cb1.getSelectedIndex());
            prep_stm.setFloat(5, Float.parseFloat(info6_tf1.getText()));
            prep_stm.setString(6, info7_tf1.getText());
            prep_stm.setString(7, info8_tf1.getText());
            prep_stm.setString(8, info9_dp1.getText());
            prep_stm.setString(9, info10_textArea1.getText());
            prep_stm.setString(10, info1_tf1.getText());
            prep_stm.executeUpdate();
            
            //insert log
            
            Statement delete_log = (Statement) connect.createStatement();
                delete_log.executeUpdate("DELETE FROM log ORDER BY date ASC limit 1");
                delete_log.close();
            
            PreparedStatement prep_stm2 = (PreparedStatement) connect.prepareStatement("INSERT INTO log(date,userid,log) VALUES(?,?,?) ");
            prep_stm2.setString(1, new SimpleDateFormat("yyyy/MM/dd HH:mm:ss").format(Calendar.getInstance().getTime()));
            prep_stm2.setString(2, UserInfo.userID);
            prep_stm2.setString(3, info1_tf1.getText()+" Student Changed");
            prep_stm2.execute();
            
            prep_stm2.close();
            prep_stm.close();
            connect.close();
            JOptionPane.showMessageDialog(rootPane, "Öğrenci Düzenlendi.");
            changeStudent.setVisible(false);
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(student_gui.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_change_buttonActionPerformed

    private void addStudentFrameWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_addStudentFrameWindowActivated
        info5_cb.removeAllItems();
        try {
            Connection connect = new db_connection().connect;
            Statement stm = (Statement) connect.createStatement();
            ResultSet rs = (ResultSet) stm.executeQuery("SELECT ogrenci_id FROM ogrenciler");
            for(int id=0; ; id++){
                if(rs.next()){
                    if(id!=rs.getInt("ogrenci_id")){
                        info1_tf.setText(id+"");
                        break;
                    }
                }else{
                    info1_tf.setText(id+"");
                    break;
                }
            }
            
            rs.close();
            
            rs = (ResultSet) stm.executeQuery("Select bolum_ismi from bolumler");
            while(rs.next()){
                info5_cb.addItem(rs.getString("bolum_ismi"));
            }
            
            connect.close();
            
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(student_gui.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_addStudentFrameWindowActivated

    private void changeStudentWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_changeStudentWindowActivated
        try {
            
            Connection connect = new db_connection().connect;
            Statement stm = (Statement) connect.createStatement();
            ResultSet rs = (ResultSet) stm.executeQuery("SELECT * FROM ogrenciler");
            while(rs.next()){
                if(rs.getInt("ogrenci_id")==selectedStudent){
                    info1_tf1.setText(String.valueOf(selectedStudent));
                    info2_tf1.setText(rs.getString("ogrenci_ismi"));
                    info3_tf1.setText(rs.getString("ogrenci_soyismi"));
                    info4_sp1.setValue(rs.getInt("ogrenci_sinifi"));
                    info5_cb1.setSelectedIndex(rs.getInt("bolum_id"));
                    info6_tf1.setText(String.valueOf(rs.getFloat("ogrenci_ortalamasi")));
                    info7_tf1.setText(rs.getString("ogrenci_email"));
                    info8_tf1.setText(rs.getString("ogrenci_telno"));
                    info9_dp1.setText(rs.getString("ogrenci_kayittarihi"));
                    info10_textArea1.setText(rs.getString("kayit_nedeni"));
                    
                }
            }
            
            connect.close();
            
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(student_gui.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_changeStudentWindowActivated

    public void search(String search_element){
        int count = 0;
        student_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Öğrenci No", "Ad", "Soyad", "Sınıf", "Bölüm İsmi", "Ortalama", "E-mail", "Tel No", "Kayıt Tarihi", "Kayıt Nedeni"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        
        DefaultTableModel model = (DefaultTableModel) student_table.getModel();
        
        try {
            Connection connect = new db_connection().connect;
            Statement stm = (Statement) connect.createStatement();
            ResultSet rs = (ResultSet) stm.executeQuery("SELECT ogrenci_id,ogrenci_ismi,ogrenci_soyismi,ogrenci_sinifi,bolum_ismi,ogrenci_ortalamasi,ogrenci_email,ogrenci_telno,ogrenci_kayittarihi,kayit_nedeni FROM ogrenciler,bolumler where bolumler.bolum_id=ogrenciler.bolum_id");
            
            while(rs.next()){
                if(String.valueOf(rs.getInt("ogrenci_id")).contains(search_element) || rs.getString("ogrenci_ismi").contains(search_element) || rs.getString("ogrenci_soyismi").contains(search_element) || String.valueOf(rs.getInt("ogrenci_sinifi")).contains(search_element) || rs.getString("bolum_ismi").contains(search_element) || String.valueOf(rs.getFloat("ogrenci_ortalamasi")).contains(search_element) || rs.getString("ogrenci_email").contains(search_element) || rs.getString("ogrenci_telno").contains(search_element) || rs.getString("ogrenci_kayittarihi").contains(search_element)||rs.getString("ogrenci_ismi").contains(search_element)){
                    model.addRow(new Object[]{
                        rs.getInt("ogrenci_id"),
                        rs.getString("ogrenci_ismi"),
                        rs.getString("ogrenci_soyismi"),
                        rs.getInt("ogrenci_sinifi"),
                        rs.getString("bolum_ismi"),
                        rs.getFloat("ogrenci_ortalamasi"),
                        rs.getString("ogrenci_email"),
                        rs.getString("ogrenci_telno"),
                        rs.getString("ogrenci_kayittarihi"),
                        rs.getString("kayit_nedeni")
                    });
                    
                    count++;
                }
            }
            
            student_table.setModel(model);
            
            JOptionPane.showMessageDialog(rootPane, "Aramanız için "+count+" kadar veri bulundu.");
            
            connect.close();
            
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(student_gui.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(student_gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(student_gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(student_gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(student_gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new student_gui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame addStudentFrame;
    private javax.swing.JButton addStudent_button;
    private javax.swing.JButton add_button;
    private javax.swing.JFrame changeStudent;
    private javax.swing.JButton change_button;
    private javax.swing.JButton delete_button;
    private javax.swing.JTextField delete_tf;
    private javax.swing.JTextArea info10_textArea;
    private javax.swing.JTextArea info10_textArea1;
    private javax.swing.JTextField info1_tf;
    private javax.swing.JTextField info1_tf1;
    private javax.swing.JTextField info2_tf;
    private javax.swing.JTextField info2_tf1;
    private javax.swing.JTextField info3_tf;
    private javax.swing.JTextField info3_tf1;
    private javax.swing.JSpinner info4_sp;
    private javax.swing.JSpinner info4_sp1;
    private javax.swing.JComboBox<String> info5_cb;
    private javax.swing.JComboBox<String> info5_cb1;
    private javax.swing.JTextField info6_tf;
    private javax.swing.JTextField info6_tf1;
    private javax.swing.JTextField info7_tf;
    private javax.swing.JTextField info7_tf1;
    private javax.swing.JTextField info8_tf;
    private javax.swing.JTextField info8_tf1;
    private com.github.lgooddatepicker.components.DatePicker info9_dp;
    private com.github.lgooddatepicker.components.DatePicker info9_dp1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton mainMenu_button;
    private javax.swing.JButton search_button;
    private javax.swing.JTable student_table;
    private javax.swing.JButton update_button;
    // End of variables declaration//GEN-END:variables
}
